#
#
#
services:
  mongodb:
    image: mongo:latest
    container_name: Team_Gateway_DBs
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootUser
      MONGO_INITDB_ROOT_PASSWORD: rootPass
